package fio

/*
 Gmsh loader.

 full disclosure: the real finicky topology stuff was generated by AI and needs to be cleaned up
*/


import "base:intrinsics"
import "core:log"
import "core:math"
import "core:mem/virtual"
import "core:slice"
import "core:strconv"
import "core:strings"

import fe "../"

GMSH_EXPECTED_MSH_VERSION :: "2.2 1 8"

@(private = "file")
Gmsh_Element_Type :: enum {
	MSH_LINE_2     = 1,
	MSH_LINE_3     = 8,
	MSH_TRIANGLE_3 = 2,
	MSH_TRIANGLE_6 = 9,
	MSH_QUAD_4     = 3,
	MSH_QUAD_9     = 10,
	MSH_TETRA_4    = 4,
	MSH_TETRA_10   = 11,
	MSH_HEX_8      = 5,
	MSH_HEX_27     = 12,
	MSH_POINT      = 15,
}

@(private = "file")
GMSH_ELEMENT_NUM_NODES := #sparse[Gmsh_Element_Type]int {
	.MSH_LINE_2     = 2,
	.MSH_LINE_3     = 3,
	.MSH_TRIANGLE_3 = 3,
	.MSH_TRIANGLE_6 = 6,
	.MSH_QUAD_4     = 4,
	.MSH_QUAD_9     = 9,
	.MSH_TETRA_4    = 4,
	.MSH_TETRA_10   = 10,
	.MSH_HEX_8      = 8,
	.MSH_HEX_27     = 27,
	.MSH_POINT      = 1,
}


@(private = "file")
SUPPORTED_ELEMENTS :: bit_set[Gmsh_Element_Type] {
	.MSH_LINE_2,
	.MSH_LINE_3,
	.MSH_TRIANGLE_3,
	.MSH_TRIANGLE_6,
	.MSH_QUAD_4,
	.MSH_QUAD_9,
	.MSH_TETRA_4,
	.MSH_TETRA_10,
	.MSH_HEX_8,
	.MSH_HEX_27,
	.MSH_POINT,
}

@(private = "file")
Raw_Element :: struct {
	type:         Gmsh_Element_Type,
	tags:         []i32,
	node_indices: []int,
}

@(private = "file")
Raw_Periodic_Link :: struct {
	dim:        int,
	slave_tag:  i32,
	master_tag: i32,
	transform:  fe.Small_Mat(4, 4, f64),
	pairs:      [][2]int, // {slave_node_idx, master_node_idx}, mesh-local indices
}

@(private = "file")
gmsh_type_to_element_info :: proc(type: Gmsh_Element_Type) -> (fe.Element_Type, fe.Order) {
	switch type {
	case .MSH_LINE_2: return .Line, .O1
	case .MSH_LINE_3: return .Line, .O2
	case .MSH_TRIANGLE_3: return .Tri, .O1
	case .MSH_TRIANGLE_6: return .Tri, .O2
	case .MSH_QUAD_4: return .Quad, .O1
	case .MSH_QUAD_9: return .Quad, .O2
	case .MSH_TETRA_4: return .Tet, .O1
	case .MSH_TETRA_10: return .Tet, .O2
	case .MSH_HEX_8: return .Hex, .O1
	case .MSH_HEX_27: return .Hex, .O2
	case .MSH_POINT: return .Point, .O1
	case: unreachable()
	}
}

@(private = "file")
Gmsh_Parser :: struct {
	data:           []u8,
	cursor:         int,
	swap_num_bytes: bool,
}

@(private = "file")
parser_consume :: proc(p: ^Gmsh_Parser) -> (u8, bool) {
	more := p.cursor < len(p.data)
	if !more {
		log.error("Gmsh: Unexpected EOF"); return 0, false
	}
	defer p.cursor += 1
	return p.data[p.cursor], true
}

@(private = "file")
ascii_line :: proc(p: ^Gmsh_Parser) -> (text: string, ok: bool) {
	start := p.cursor
	for (parser_consume(p) or_return) != '\n' {  }
	text = cast(string)p.data[start:p.cursor]
	return strings.trim_space(text), true
}


@(private = "file")
expect_ascii_line :: proc(p: ^Gmsh_Parser, text: string) -> bool {
	got := ascii_line(p) or_return
	if got == text { return true }
	log.errorf("Gmsh: Expected %s, got %s", text, got)
	return false
}

@(private = "file")
parse_int :: proc(text: string) -> (n: int, ok: bool) {
	n, ok = strconv.parse_int(text)

	if !ok { log.errorf("Gmsh: Expected integer got %s", text) }

	return n, ok
}

@(private = "file")
read_number :: proc($T: typeid, p: ^Gmsh_Parser) -> (n: T, ok: bool) {
	bytes: [size_of(T)]u8
	for i in 0 ..< size_of(T) { bytes[i] = parser_consume(p) or_return }

	t := (cast(^T)raw_data(bytes[:]))^
	if p.swap_num_bytes { t = intrinsics.byte_swap(t) }

	return t, true
}

gmsh_load_mesh :: proc(mesh_data: []u8, mesh: ^fe.Mesh) -> bool {
	context.temp_allocator = fe.scratch()
	fe.scratch_guard()

	context.allocator = virtual.arena_allocator(&mesh.arena)

	p := Gmsh_Parser {
		data = mesh_data,
	}

	{
		expect_ascii_line(&p, "$MeshFormat") or_return
		expect_ascii_line(&p, GMSH_EXPECTED_MSH_VERSION) or_return
		endianess := read_number(i32, &p) or_return
		p.swap_num_bytes = endianess != 1
		parser_consume(&p) or_return // newline between above number and mesh format text
		expect_ascii_line(&p, "$EndMeshFormat") or_return
	}

	for &names in mesh.tag_names { names = make(map[string]fe.Tag_ID) }

	{
		expect_ascii_line(&p, "$PhysicalNames") or_return
		num_groups := parse_int(ascii_line(&p) or_return) or_return

		max_dimension: int
		for _ in 0 ..< num_groups {
			line := ascii_line(&p) or_return

			components := strings.split(line, " ", context.temp_allocator)
			if len(components) < 3 { return false }

			group_dim := parse_int(components[0]) or_return
			if group_dim > max_dimension { max_dimension = group_dim }

			id := parse_int(components[1]) or_return
			if id >= fe.MAX_TAGS {
				log.errorf("Gmsh: physical group id %d, ids must be < %d", id, fe.MAX_TAGS)
				return false
			}
			name := strings.clone(strings.trim(components[2], "\""))
			mesh.tag_names[fe.Dimension(group_dim)][name] = fe.Tag_ID(id)
		}
		expect_ascii_line(&p, "$EndPhysicalNames") or_return

		mesh.intrinsic_dim = fe.Dimension(max_dimension)
	}

	gmsh_id_to_node_id := make(map[i32]int, context.temp_allocator)
	{
		expect_ascii_line(&p, "$Nodes") or_return
		num_nodes := parse_int(ascii_line(&p) or_return) or_return

		mesh.nodes = make([][3]f64, num_nodes)

		for i in 0 ..< num_nodes {
			id := read_number(i32, &p) or_return
			x := read_number(f64, &p) or_return
			y := read_number(f64, &p) or_return
			z := read_number(f64, &p) or_return
			gmsh_id_to_node_id[id] = i
			mesh.nodes[i] = {x, y, z}
		}
		parser_consume(&p) or_return
		expect_ascii_line(&p, "$EndNodes") or_return
	}

	raw_primary_elements := make([dynamic]Raw_Element, context.temp_allocator)
	raw_facet_elements := make([dynamic]Raw_Element, context.temp_allocator)
	skipped := 0
	{
		expect_ascii_line(&p, "$Elements") or_return
		num_elements := parse_int(ascii_line(&p) or_return) or_return

		for elements_read: i32 = 0; elements_read < i32(num_elements); {
			type_integer := read_number(i32, &p) or_return
			num_in_group := read_number(i32, &p) or_return
			num_tags := read_number(i32, &p) or_return

			type := Gmsh_Element_Type(type_integer)
			if type not_in SUPPORTED_ELEMENTS {
				log.errorf("Element type %s is not supported.", type)
				return false
			}

			fem_type, order := gmsh_type_to_element_info(type)

			if elements_read == 0 { mesh.order = order }

			if order != mesh.order {
				log.errorf("Mesh must be consistent order, expected %v, got %v", mesh.order, order)
				return false
			}

			el_dim := fe.element_dim(fem_type)

			for _ in 0 ..< num_in_group {
				elements_read += 1
				element: Raw_Element
				element.type = type
				_ = read_number(i32, &p) or_return //id

				element.tags = make([]i32, max(int(num_tags), 1), context.temp_allocator) // [physical, elementary], 0 = none
				for j in 0 ..< int(num_tags) {
					element.tags[j] = read_number(i32, &p) or_return
				}
				if element.tags[0] < 0 || int(element.tags[0]) >= fe.MAX_TAGS {
					log.errorf("Gmsh: physical group id %d, ids must be < %d", element.tags[0], fe.MAX_TAGS)
					return false
				}

				node_count := GMSH_ELEMENT_NUM_NODES[type]
				element.node_indices = make([]int, node_count)

				for j in 0 ..< node_count {
					node_idx := read_number(i32, &p) or_return
					node_id := gmsh_id_to_node_id[node_idx]
					element.node_indices[j] = node_id
				}

				switch {
				case el_dim == mesh.intrinsic_dim:
					append(&raw_primary_elements, element)
					mesh.encountered_cell_types += {fem_type}
				case int(el_dim) == int(mesh.intrinsic_dim) - 1: append(&raw_facet_elements, element)
				case: skipped += 1
				}
			}
		}
	}
	if skipped > 0 { log.warnf("Gmsh: skipped %d elements below facet dimension, they can't be tagged", skipped) }

	parser_consume(&p) or_return // newline after last binary element data
	expect_ascii_line(&p, "$EndElements") or_return


	raw_periodic_links := make([dynamic]Raw_Periodic_Link, context.temp_allocator)
	if p.cursor < len(p.data) {
		periodic_start := p.cursor
		line, has_line := ascii_line(&p)

		if has_line && line == "$Periodic" {
			num_links := parse_int(ascii_line(&p) or_return) or_return

			for _ in 0 ..< num_links {
				header := strings.split(ascii_line(&p) or_return, " ", context.temp_allocator)
				if len(header) < 3 {
					log.error("Gmsh: malformed $Periodic entity header")
					return false
				}

				link: Raw_Periodic_Link
				link.dim = parse_int(header[0]) or_return
				link.slave_tag = i32(parse_int(header[1]) or_return)
				link.master_tag = i32(parse_int(header[2]) or_return)
				for i in 0 ..< 4 { link.transform.data[i][i] = 1 } 	// identity unless overridden below

				affine_start := p.cursor
				maybe_affine, has_affine_line := ascii_line(&p)
				if has_affine_line && strings.has_prefix(maybe_affine, "Affine") {
					raw_values := strings.split(
						strings.trim_space(maybe_affine[len("Affine"):]),
						" ",
						context.temp_allocator,
					)
					values := make([dynamic]f64, context.temp_allocator)
					for raw_v in raw_values {
						trimmed := strings.trim_space(raw_v)
						if len(trimmed) == 0 { continue }
						v, vok := strconv.parse_f64(trimmed)
						if !vok {
							log.errorf("Gmsh: bad $Periodic affine value %s", trimmed)
							return false
						}
						append(&values, v)
					}
					if len(values) != 12 && len(values) != 16 {
						log.errorf("Gmsh: $Periodic affine transform expected 12 or 16 values, got %d", len(values))
						return false
					}

					rows := 3 if len(values) == 12 else 4
					idx := 0
					for r in 0 ..< rows {
						for c in 0 ..< 4 {
							link.transform.data[c][r] = values[idx]
							idx += 1
						}
					}
					if rows == 3 {
						link.transform.data[0][3] = 0
						link.transform.data[1][3] = 0
						link.transform.data[2][3] = 0
						link.transform.data[3][3] = 1
					}
				} else {
					p.cursor = affine_start
				}

				num_nodes := parse_int(ascii_line(&p) or_return) or_return
				pairs := make([][2]int, num_nodes)
				for i in 0 ..< num_nodes {
					node_line := strings.split(ascii_line(&p) or_return, " ", context.temp_allocator)
					if len(node_line) < 2 {
						log.error("Gmsh: malformed $Periodic node correspondence line")
						return false
					}

					slave_gid := i32(parse_int(node_line[0]) or_return)
					master_gid := i32(parse_int(node_line[1]) or_return)

					slave_idx, slave_found := gmsh_id_to_node_id[slave_gid]
					master_idx, master_found := gmsh_id_to_node_id[master_gid]
					if !slave_found || !master_found {
						log.errorf(
							"Gmsh: $Periodic node reference (%d, %d) not found among mesh nodes",
							slave_gid,
							master_gid,
						)
						return false
					}
					pairs[i] = {slave_idx, master_idx}
				}
				link.pairs = pairs

				append(&raw_periodic_links, link)
			}

			expect_ascii_line(&p, "$EndPeriodic") or_return
		} else {
			p.cursor = periodic_start
		}
	}

	return gmsh_build_topology(mesh, raw_primary_elements[:], raw_facet_elements[:], raw_periodic_links[:])
}

//== Gmsh node order -> reference node order

// Reference coordinates of each gmsh node, in gmsh's local order. Gmsh's reference cells coincide with ours
// (Line/Quad/Hex on [-1, 1], Tri/Tet unit simplices); only the numbering differs. Order-1 types use the prefix.
@(private = "file", rodata)
GMSH_LINE := [?]fe.Ref_Vec{{-1, 0, 0}, {1, 0, 0}, {0, 0, 0}}

@(private = "file", rodata)
GMSH_TRI := [?]fe.Ref_Vec{{0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0.5, 0, 0}, {0.5, 0.5, 0}, {0, 0.5, 0}}

@(private = "file", rodata)
GMSH_QUAD := [?]fe.Ref_Vec {
	{-1, -1, 0}, {1, -1, 0}, {1, 1, 0}, {-1, 1, 0}, // vertices
	{0, -1, 0}, {1, 0, 0}, {0, 1, 0}, {-1, 0, 0}, // edges 0-1, 1-2, 2-3, 3-0
	{0, 0, 0},
}

@(private = "file", rodata)
GMSH_TET := [?]fe.Ref_Vec {
	{0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0, 0, 1}, // vertices
	{0.5, 0, 0}, {0.5, 0.5, 0}, {0, 0.5, 0}, {0, 0, 0.5}, {0, 0.5, 0.5}, {0.5, 0, 0.5}, // edges 0-1, 1-2, 2-0, 3-0, 3-2, 3-1
}

@(private = "file", rodata)
GMSH_HEX := [?]fe.Ref_Vec {
	{-1, -1, -1}, {1, -1, -1}, {1, 1, -1}, {-1, 1, -1}, {-1, -1, 1}, {1, -1, 1}, {1, 1, 1}, {-1, 1, 1}, // vertices
	{0, -1, -1}, {-1, 0, -1}, {-1, -1, 0}, {1, 0, -1}, {1, -1, 0}, {0, 1, -1}, // edges 0-1, 0-3, 0-4, 1-2, 1-5, 2-3
	{1, 1, 0}, {-1, 1, 0}, {0, -1, 1}, {-1, 0, 1}, {1, 0, 1}, {0, 1, 1}, // edges 2-6, 3-7, 4-5, 4-7, 5-6, 6-7
	{0, 0, -1}, {0, -1, 0}, {-1, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0, 0, 1}, // faces z-, y-, x-, x+, y+, z+
	{0, 0, 0},
}

@(private = "file", rodata)
GMSH_POINT := [?]fe.Ref_Vec{{0, 0, 0}}

@(private = "file")
gmsh_ref_nodes :: proc(type: Gmsh_Element_Type) -> []fe.Ref_Vec {
	n := GMSH_ELEMENT_NUM_NODES[type]
	#partial switch type {
	case .MSH_LINE_2, .MSH_LINE_3: return GMSH_LINE[:n]
	case .MSH_TRIANGLE_3, .MSH_TRIANGLE_6: return GMSH_TRI[:n]
	case .MSH_QUAD_4, .MSH_QUAD_9: return GMSH_QUAD[:n]
	case .MSH_TETRA_4, .MSH_TETRA_10: return GMSH_TET[:n]
	case .MSH_HEX_8, .MSH_HEX_27: return GMSH_HEX[:n]
	case .MSH_POINT: return GMSH_POINT[:]
	}
	unreachable()
}

// perm[reference local node] = gmsh local node. Cached per gmsh type.
@(private = "file")
node_perm :: proc(cache: ^map[Gmsh_Element_Type][]int, type: Gmsh_Element_Type) -> (perm: []int, ok: bool) {
	if p, found := cache[type]; found { return p, true }

	et, order := gmsh_type_to_element_info(type)
	ref := fe.basis_nodal_coords({et, .Lagrange, order}, context.temp_allocator)
	gmsh := gmsh_ref_nodes(type)
	if len(ref) != len(gmsh) {
		log.errorf("Gmsh: %v has %d nodes, reference element expects %d", type, len(gmsh), len(ref))
		return nil, false
	}

	perm = make([]int, len(ref), context.temp_allocator)
	for r, i in ref {
		perm[i] = -1
		for g, j in gmsh {
			diff := g - r
			if abs(diff[0]) + abs(diff[1]) + abs(diff[2]) < 1e-12 { perm[i] = j; break }
		}
		if perm[i] < 0 {
			log.errorf("Gmsh: no %v node at reference position %v", type, r)
			return nil, false
		}
	}
	cache[type] = perm
	return perm, true
}

//== Topology

@(private = "file")
Vertex_Key :: [fe.MAX_VERTICES]int

@(private = "file")
vertex_key :: proc(ids: []$T) -> (key: Vertex_Key) {
	slice.fill(key[:], max(int))
	for v, i in ids { key[i] = int(v) }
	slice.sort(key[:len(ids)])
	return
}

// Edges or faces, deduplicated by vertex set.
@(private = "file")
Entity_Table :: struct {
	ids:       map[Vertex_Key]fe.Entity_ID,
	canonical: [dynamic][]fe.Entity_ID, // vertex ids in canonical order
	types:     [dynamic]fe.Element_Type,
}

@(private = "file")
entity_lookup :: proc(t: ^Entity_Table, et: fe.Element_Type, verts: []fe.Entity_ID) -> fe.Entity_ID {
	key := vertex_key(verts)
	if id, ok := t.ids[key]; ok { return id }
	id := fe.Entity_ID(len(t.canonical))
	canon := fe.element_canonical_order(et, verts)
	t.ids[key] = id
	append(&t.canonical, slice.clone(canon[:len(verts)], context.temp_allocator))
	append(&t.types, et)
	return id
}

@(private = "file")
Topology :: struct {
	fd:             fe.Dimension,
	vertex_of_node: map[int]fe.Entity_ID, // corner nodes only
	tables:         [fe.Dimension]Entity_Table, // dims 1 ..< cell dim
}

// Ids and keys of an entity's edges and faces from its vertex ids, adding new ones to the tables.
@(private = "file")
set_sub_entities :: proc(topo: ^Topology, e: ^fe.Entity) {
	for d in fe.Dimension {
		if d == .D0 || d >= fe.element_dim(e.type) { continue }
		e.conn[d] = make([]fe.Entity_ID, fe.element_n_sub_entities(e.type, d))
		for &id, k in e.conn[d] {
			sub := fe.element_sub_entity(e.type, d, k)
			verts: [fe.MAX_VERTICES]fe.Entity_ID
			n := len(sub.closure[.D0])
			for v, i in sub.closure[.D0] { verts[i] = e.conn[.D0][v] }
			id = entity_lookup(&topo.tables[d], sub.type, verts[:n])
			e.keys[d][k] = fe.element_orientation(sub.type, verts[:n], topo.tables[d].canonical[id][:])
		}
	}
}

// Facet id of a gmsh element whose first nodes are the facet's vertices.
@(private = "file")
find_facet :: proc(topo: ^Topology, type: fe.Element_Type, node_indices: []int) -> (id: fe.Entity_ID, ok: bool) {
	nv := fe.element_n_sub_entities(type, .D0)
	verts: [fe.MAX_VERTICES]fe.Entity_ID
	for i in 0 ..< nv { verts[i] = topo.vertex_of_node[node_indices[i]] or_return }
	if topo.fd == .D0 { return verts[0], true }
	return topo.tables[topo.fd].ids[vertex_key(verts[:nv])]
}

@(private = "file")
gmsh_build_topology :: proc(
	mesh: ^fe.Mesh,
	primary: []Raw_Element,
	facet_elems: []Raw_Element,
	periodic_links: []Raw_Periodic_Link,
) -> bool {
	if mesh.intrinsic_dim < .D1 {
		log.error("Gmsh: mesh must be at least 1D to build topology")
		return false
	}
	cd := mesh.intrinsic_dim

	topo := Topology {
		fd             = cd - fe.Dimension(1),
		vertex_of_node = make(map[int]fe.Entity_ID, context.temp_allocator),
	}
	for &t in topo.tables {
		t.ids = make(map[Vertex_Key]fe.Entity_ID, context.temp_allocator)
		t.canonical = make([dynamic][]fe.Entity_ID, context.temp_allocator)
		t.types = make([dynamic]fe.Element_Type, context.temp_allocator)
	}
	perms := make(map[Gmsh_Element_Type][]int, context.temp_allocator)

	//== Cells

	cells := make([dynamic]fe.Entity, 0, len(primary))
	cell_nodes := make([dynamic][]fe.Entity_ID, 0, len(primary))
	cell_of := make(map[Vertex_Key]int, context.temp_allocator)

	for elem in primary {
		et, _ := gmsh_type_to_element_info(elem.type)
		nv := fe.element_n_sub_entities(et, .D0)

		// v2 writes an element once per physical group it is in
		key := vertex_key(elem.node_indices[:nv])
		if ci, dup := cell_of[key]; dup {
			cells[ci].tags += {int(elem.tags[0])}
			continue
		}
		cell_of[key] = len(cells)

		perm := node_perm(&perms, elem.type) or_return
		nodes := make([]fe.Entity_ID, len(perm))
		for g, i in perm { nodes[i] = fe.Entity_ID(elem.node_indices[g]) }

		cell := fe.Entity {
			id   = fe.Entity_ID(len(cells)),
			type = et,
			tags = {int(elem.tags[0])},
		}
		cell.conn[.D0] = make([]fe.Entity_ID, nv)
		for &v, i in cell.conn[.D0] {
			node := int(nodes[i])
			id, found := topo.vertex_of_node[node]
			if !found {
				id = fe.Entity_ID(len(topo.vertex_of_node))
				topo.vertex_of_node[node] = id
			}
			v = id
		}
		set_sub_entities(&topo, &cell)
		cell.conn[cd] = make([]fe.Entity_ID, 1)
		cell.conn[cd][0] = cell.id

		append(&cells, cell)
		append(&cell_nodes, nodes)
	}

	mesh.cells = cells[:]
	mesh.cell_nodes = cell_nodes[:]
	mesh.n_entities[.D0] = len(topo.vertex_of_node)
	for d in fe.Dimension {
		if d != .D0 && d < cd { mesh.n_entities[d] = len(topo.tables[d].canonical) }
	}
	mesh.n_entities[cd] = len(cells)

	//== Facets

	fd := topo.fd
	facets := make([]fe.Entity, mesh.n_entities[fd])

	counts := make([]int, len(facets), context.temp_allocator)
	n_cofaces := 0
	for cell in cells {
		for f in cell.conn[fd] { counts[f] += 1 }
		n_cofaces += len(cell.conn[fd])
	}
	all_cofaces := make([]fe.Coface, n_cofaces)
	total := 0
	for &facet, f in facets {
		facet.cofaces = all_cofaces[total:][:counts[f]]
		total += counts[f]
		counts[f] = 0
	}
	for cell in cells {
		for f, i in cell.conn[fd] {
			facets[f].cofaces[counts[f]] = {cell.id, i}
			counts[f] += 1
		}
	}

	for &facet, f in facets {
		facet.id = fe.Entity_ID(f)
		if fd == .D0 {
			facet.type = .Point
			facet.conn[.D0] = make([]fe.Entity_ID, 1)
			facet.conn[.D0][0] = facet.id
			continue
		}
		facet.type = topo.tables[fd].types[f]
		facet.conn[.D0] = slice.clone(topo.tables[fd].canonical[f])
		set_sub_entities(&topo, &facet)
		facet.conn[fd] = make([]fe.Entity_ID, 1)
		facet.conn[fd][0] = facet.id
	}

	for elem in facet_elems {
		ft, _ := gmsh_type_to_element_info(elem.type)
		f, found := find_facet(&topo, ft, elem.node_indices)
		if !found {
			log.errorf("Gmsh: facet element (nodes=%v) does not match any facet", elem.node_indices)
			return false
		}
		facets[f].tags += {int(elem.tags[0])}
	}

	mesh.facets = facets
	mesh.entities[cd] = mesh.cells
	mesh.entities[fd] = mesh.facets

	if len(periodic_links) > 0 {
		mesh.periodics = gmsh_build_periodicity(mesh, &topo, facet_elems, periodic_links) or_return
	}
	return true
}

// Links every entity on the master boundary to the slave entity its vertices map onto, once per entity. The key is
// element_orientation(type, master's canonical vertices as slave ids, slave's canonical vertices).
@(private = "file")
gmsh_build_periodicity :: proc(
	mesh: ^fe.Mesh,
	topo: ^Topology,
	facet_elems: []Raw_Element,
	links: []Raw_Periodic_Link,
) -> (
	periodics: []fe.Periodicity,
	ok: bool,
) {
	tag_of_entity := make(map[i32]fe.Tag_ID, context.temp_allocator)
	for elem in facet_elems {
		if len(elem.tags) < 2 { continue }
		tag_of_entity[elem.tags[1]] = fe.Tag_ID(elem.tags[0])
	}

	result := make([]fe.Periodicity, len(links))

	for link, li in links {
		// Vertex correspondence both ways (high-order nodes are not vertices and are skipped).
		slave_of := make(map[fe.Entity_ID]fe.Entity_ID, context.temp_allocator)
		master_of := make(map[fe.Entity_ID]fe.Entity_ID, context.temp_allocator)
		for pr in link.pairs {
			sv, s_ok := topo.vertex_of_node[pr[0]]
			mv, m_ok := topo.vertex_of_node[pr[1]]
			if s_ok && m_ok {
				slave_of[mv] = sv
				master_of[sv] = mv
			}
		}

		per_links: [fe.Dimension][dynamic]fe.Entity_Link
		seen: [fe.Dimension]map[fe.Entity_ID]bool
		for d in fe.Dimension { seen[d] = make(map[fe.Entity_ID]bool, context.temp_allocator) }

		for elem in facet_elems {
			if len(elem.tags) < 2 || elem.tags[1] != link.slave_tag { continue }
			et, _ := gmsh_type_to_element_info(elem.type)

			slave, found_slave := find_facet(topo, et, elem.node_indices)
			if !found_slave {
				log.errorf("Gmsh: $Periodic slave element (nodes=%v) does not match any facet", elem.node_indices)
				return nil, false
			}
			sc := mesh.facets[slave].conn[.D0]
			mverts: [fe.MAX_VERTICES]fe.Entity_ID
			for v, i in sc {
				mverts[i] = master_of[v] or_else -1
				if mverts[i] < 0 {
					log.errorf("Gmsh: $Periodic vertex %d has no master correspondence", v)
					return nil, false
				}
			}
			master: fe.Entity_ID
			found_master: bool
			if topo.fd == .D0 {
				master, found_master = mverts[0], true
			} else {
				master, found_master = topo.tables[topo.fd].ids[vertex_key(mverts[:len(sc)])]
			}
			if !found_master {
				log.errorf("Gmsh: $Periodic master facet (verts=%v) does not match any facet", mverts[:len(sc)])
				return nil, false
			}

			for d in fe.Dimension {
				if d > topo.fd { break }
				for gid in mesh.facets[master].conn[d] {
					if seen[d][gid] { continue }
					seen[d][gid] = true
					if d == .D0 {
						append(&per_links[d], fe.Entity_Link{master = gid, slave = slave_of[gid]})
						continue
					}
					t := &topo.tables[d]
					mcanon := t.canonical[gid]
					translated: [fe.MAX_VERTICES]fe.Entity_ID
					for v, i in mcanon { translated[i] = slave_of[v] }
					s_id, found := t.ids[vertex_key(translated[:len(mcanon)])]
					if !found {
						log.errorf("Gmsh: $Periodic entity %d (dim %v) has no slave image", gid, d)
						return nil, false
					}
					key := fe.element_orientation(t.types[gid], translated[:len(mcanon)], t.canonical[s_id])
					append(&per_links[d], fe.Entity_Link{master = gid, slave = s_id, key = key})
				}
			}
		}

		result[li] = fe.Periodicity {
			slave     = tag_of_entity[link.slave_tag] or_else 0,
			master    = tag_of_entity[link.master_tag] or_else 0,
			transform = link.transform,
		}
		for d in fe.Dimension { result[li].links[d] = per_links[d][:] }
	}

	return result, true
}
