package fio

/*
 Gmsh loader.

 full disclosure: the real finicky topology stuff was generated by AI and needs to be cleaned up
*/


import "base:intrinsics"
import "core:log"
import "core:math"
import "core:mem/virtual"
import "core:slice"
import "core:strconv"
import "core:strings"

import fe "../"

GMSH_EXPECTED_MSH_VERSION :: "2.2 1 8"

@(private = "file")
ALIGNMENT_TOLERANCE :: 1e-12

@(private = "file")
Gmsh_Element_Type :: enum {
	MSH_LINE_2     = 1,
	MSH_LINE_3     = 8,
	MSH_TRIANGLE_3 = 2,
	MSH_TRIANGLE_6 = 9,
	MSH_QUAD_4     = 3,
	MSH_QUAD_9     = 10,
	MSH_TETRA_4    = 4,
	MSH_TETRA_10   = 11,
	MSH_HEX_8      = 5,
	MSH_HEX_27     = 12,
	MSH_POINT      = 15,
}

@(private = "file")
GMSH_ELEMENT_NUM_NODES := #sparse[Gmsh_Element_Type]int {
	.MSH_LINE_2     = 2,
	.MSH_LINE_3     = 3,
	.MSH_TRIANGLE_3 = 3,
	.MSH_TRIANGLE_6 = 6,
	.MSH_QUAD_4     = 4,
	.MSH_QUAD_9     = 9,
	.MSH_TETRA_4    = 4,
	.MSH_TETRA_10   = 10,
	.MSH_HEX_8      = 8,
	.MSH_HEX_27     = 27,
	.MSH_POINT      = 1,
}


@(private = "file")
SUPPORTED_ELEMENTS :: bit_set[Gmsh_Element_Type] {
	.MSH_LINE_2,
	.MSH_LINE_3,
	.MSH_TRIANGLE_3,
	.MSH_TRIANGLE_6,
	.MSH_QUAD_4,
	.MSH_QUAD_9,
	.MSH_TETRA_4,
	.MSH_TETRA_10,
	.MSH_HEX_8,
	.MSH_HEX_27,
	.MSH_POINT,
}

@(private = "file")
Raw_Element :: struct {
	type:         Gmsh_Element_Type,
	tags:         []i32,
	node_indices: []int,
}

@(private = "file")
Raw_Periodic_Link :: struct {
	dim:        int,
	slave_tag:  i32,
	master_tag: i32,
	transform:  fe.Small_Mat(4, 4, f64),
	pairs:      [][2]int, // {slave_node_idx, master_node_idx}, mesh-local indices
}

@(private = "file")
gmsh_type_to_element_info :: proc(type: Gmsh_Element_Type) -> (fe.Element_Type, fe.Order) {
	switch type {
	case .MSH_LINE_2: return .Line, .O1
	case .MSH_LINE_3: return .Line, .O2
	case .MSH_TRIANGLE_3: return .Tri, .O1
	case .MSH_TRIANGLE_6: return .Tri, .O2
	case .MSH_QUAD_4: return .Quad, .O1
	case .MSH_QUAD_9: return .Quad, .O2
	case .MSH_TETRA_4: return .Tet, .O1
	case .MSH_TETRA_10: return .Tet, .O2
	case .MSH_HEX_8: return .Hex, .O1
	case .MSH_HEX_27: return .Hex, .O2
	case .MSH_POINT: return .Point, .O1
	case: unreachable()
	}
}

@(private = "file")
Gmsh_Parser :: struct {
	data:           []u8,
	cursor:         int,
	swap_num_bytes: bool,
}

@(private = "file")
parser_consume :: proc(p: ^Gmsh_Parser) -> (u8, bool) {
	more := p.cursor < len(p.data)
	if !more {
		log.error("Gmsh: Unexpected EOF"); return 0, false
	}
	defer p.cursor += 1
	return p.data[p.cursor], true
}

@(private = "file")
ascii_line :: proc(p: ^Gmsh_Parser) -> (text: string, ok: bool) {
	start := p.cursor
	for (parser_consume(p) or_return) != '\n' {  }
	text = cast(string)p.data[start:p.cursor]
	return strings.trim_space(text), true
}


@(private = "file")
expect_ascii_line :: proc(p: ^Gmsh_Parser, text: string) -> bool {
	got := ascii_line(p) or_return
	if got == text { return true }
	log.errorf("Gmsh: Expected %s, got %s", text, got)
	return false
}

@(private = "file")
parse_int :: proc(text: string) -> (n: int, ok: bool) {
	n, ok = strconv.parse_int(text)

	if !ok { log.errorf("Gmsh: Expected integer got %s", text) }

	return n, ok
}

@(private = "file")
read_number :: proc($T: typeid, p: ^Gmsh_Parser) -> (n: T, ok: bool) {
	bytes: [size_of(T)]u8
	for i in 0 ..< size_of(T) { bytes[i] = parser_consume(p) or_return }

	t := (cast(^T)raw_data(bytes[:]))^
	if p.swap_num_bytes { t = intrinsics.byte_swap(t) }

	return t, true
}

gmsh_load_mesh :: proc(mesh_data: []u8, mesh: ^fe.Mesh) -> bool {
	context.temp_allocator = fe.scratch()
	fe.scratch_guard()

	context.allocator = virtual.arena_allocator(&mesh.arena)

	p := Gmsh_Parser {
		data = mesh_data,
	}

	{
		expect_ascii_line(&p, "$MeshFormat") or_return
		expect_ascii_line(&p, GMSH_EXPECTED_MSH_VERSION) or_return
		endianess := read_number(i32, &p) or_return
		p.swap_num_bytes = endianess != 1
		parser_consume(&p) or_return // newline between above number and mesh format text
		expect_ascii_line(&p, "$EndMeshFormat") or_return
	}

	mesh.boundary_names = make(map[string]fe.Boundary_ID)
	mesh.region_names = make(map[string]fe.Region_ID)

	names := make(map[string]struct {
			id:  int,
			dim: fe.Dimension,
		}, context.temp_allocator)

	{
		expect_ascii_line(&p, "$PhysicalNames") or_return
		num_groups := parse_int(ascii_line(&p) or_return) or_return

		max_dimension: int
		for _ in 0 ..< num_groups {
			line := ascii_line(&p) or_return

			components := strings.split(line, " ", context.temp_allocator)
			if len(components) < 3 { return false }

			group_dim := parse_int(components[0]) or_return
			if group_dim > max_dimension { max_dimension = group_dim }

			name := strings.clone(strings.trim(components[2], "\""))
			names[name] = {parse_int(components[1]) or_return, fe.Dimension(group_dim)}
		}
		expect_ascii_line(&p, "$EndPhysicalNames") or_return

		mesh.intrinsic_dim = fe.Dimension(max_dimension)

		for key, value in names {
			if value.dim < mesh.intrinsic_dim {
				mesh.boundary_names[key] = fe.Boundary_ID(value.id)
			} else {
				mesh.region_names[key] = fe.Region_ID(value.id)
			}
		}
	}

	gmsh_id_to_node_id := make(map[i32]int, context.temp_allocator)
	{
		expect_ascii_line(&p, "$Nodes") or_return
		num_nodes := parse_int(ascii_line(&p) or_return) or_return

		mesh.nodes = make([][3]f64, num_nodes)

		for i in 0 ..< num_nodes {
			id := read_number(i32, &p) or_return
			x := read_number(f64, &p) or_return
			y := read_number(f64, &p) or_return
			z := read_number(f64, &p) or_return
			gmsh_id_to_node_id[id] = i
			mesh.nodes[i] = {x, y, z}
		}
		parser_consume(&p) or_return
		expect_ascii_line(&p, "$EndNodes") or_return
	}

	raw_primary_elements := make([dynamic]Raw_Element, context.temp_allocator)
	raw_boundary_elements := make([dynamic]Raw_Element, context.temp_allocator)
	{
		expect_ascii_line(&p, "$Elements") or_return
		num_elements := parse_int(ascii_line(&p) or_return) or_return

		for elements_read: i32 = 0; elements_read < i32(num_elements); {
			type_integer := read_number(i32, &p) or_return
			num_in_group := read_number(i32, &p) or_return
			num_tags := read_number(i32, &p) or_return

			type := Gmsh_Element_Type(type_integer)
			if type not_in SUPPORTED_ELEMENTS {
				log.errorf("Element type %s is not supported.", type)
				return false
			}

			fem_type, order := gmsh_type_to_element_info(type)

			if elements_read == 0 { mesh.order = order }

			if order != mesh.order {
				log.errorf("Mesh must be consistent order, expected %v, got %v", mesh.order, order)
				return false
			}

			el_dim := fe.element_dim(fem_type)

			for _ in 0 ..< num_in_group {
				elements_read += 1
				element: Raw_Element
				element.type = type
				_ = read_number(i32, &p) or_return //id

				if num_tags == 0 {
					if el_dim < mesh.intrinsic_dim { log.warn("Untagged boundary element, defaulting to id 0") }
					element.tags = make([]i32, 1, context.temp_allocator)
					element.tags[0] = 0
				} else {
					element.tags = make([]i32, num_tags, context.temp_allocator)
					for j in 0 ..< len(element.tags) {
						element.tags[j] = read_number(i32, &p) or_return
					}
				}

				node_count := GMSH_ELEMENT_NUM_NODES[type]
				element.node_indices = make([]int, node_count)

				for j in 0 ..< node_count {
					node_idx := read_number(i32, &p) or_return
					node_id := gmsh_id_to_node_id[node_idx]
					element.node_indices[j] = node_id
				}

				#partial switch el_dim {
				case fe.Dimension(int(mesh.intrinsic_dim) - 1): append(&raw_boundary_elements, element)
				case mesh.intrinsic_dim:
					append(&raw_primary_elements, element)
					mesh.encountered_cell_types += {fem_type}
				case:
					log.errorf(
						"Gmsh: Found a mesh element dim %v that was inconsistent with the dimensions of the mesh %v.",
						el_dim,
						mesh.intrinsic_dim,
					)
					return false
				}
			}
		}
	}

	parser_consume(&p) or_return // newline after last binary element data
	expect_ascii_line(&p, "$EndElements") or_return


	raw_periodic_links := make([dynamic]Raw_Periodic_Link, context.temp_allocator)
	if p.cursor < len(p.data) {
		periodic_start := p.cursor
		line, has_line := ascii_line(&p)

		if has_line && line == "$Periodic" {
			num_links := parse_int(ascii_line(&p) or_return) or_return

			for _ in 0 ..< num_links {
				header := strings.split(ascii_line(&p) or_return, " ", context.temp_allocator)
				if len(header) < 3 {
					log.error("Gmsh: malformed $Periodic entity header")
					return false
				}

				link: Raw_Periodic_Link
				link.dim = parse_int(header[0]) or_return
				link.slave_tag = i32(parse_int(header[1]) or_return)
				link.master_tag = i32(parse_int(header[2]) or_return)
				for i in 0 ..< 4 { link.transform.data[i][i] = 1 } 	// identity unless overridden below

				affine_start := p.cursor
				maybe_affine, has_affine_line := ascii_line(&p)
				if has_affine_line && strings.has_prefix(maybe_affine, "Affine") {
					raw_values := strings.split(
						strings.trim_space(maybe_affine[len("Affine"):]),
						" ",
						context.temp_allocator,
					)
					values := make([dynamic]f64, context.temp_allocator)
					for raw_v in raw_values {
						trimmed := strings.trim_space(raw_v)
						if len(trimmed) == 0 { continue }
						v, vok := strconv.parse_f64(trimmed)
						if !vok {
							log.errorf("Gmsh: bad $Periodic affine value %s", trimmed)
							return false
						}
						append(&values, v)
					}
					if len(values) != 12 && len(values) != 16 {
						log.errorf("Gmsh: $Periodic affine transform expected 12 or 16 values, got %d", len(values))
						return false
					}

					rows := 3 if len(values) == 12 else 4
					idx := 0
					for r in 0 ..< rows {
						for c in 0 ..< 4 {
							link.transform.data[c][r] = values[idx]
							idx += 1
						}
					}
					if rows == 3 {
						link.transform.data[0][3] = 0
						link.transform.data[1][3] = 0
						link.transform.data[2][3] = 0
						link.transform.data[3][3] = 1
					}
				} else {
					p.cursor = affine_start
				}

				num_nodes := parse_int(ascii_line(&p) or_return) or_return
				pairs := make([][2]int, num_nodes)
				for i in 0 ..< num_nodes {
					node_line := strings.split(ascii_line(&p) or_return, " ", context.temp_allocator)
					if len(node_line) < 2 {
						log.error("Gmsh: malformed $Periodic node correspondence line")
						return false
					}

					slave_gid := i32(parse_int(node_line[0]) or_return)
					master_gid := i32(parse_int(node_line[1]) or_return)

					slave_idx, slave_found := gmsh_id_to_node_id[slave_gid]
					master_idx, master_found := gmsh_id_to_node_id[master_gid]
					if !slave_found || !master_found {
						log.errorf(
							"Gmsh: $Periodic node reference (%d, %d) not found among mesh nodes",
							slave_gid,
							master_gid,
						)
						return false
					}
					pairs[i] = {slave_idx, master_idx}
				}
				link.pairs = pairs

				append(&raw_periodic_links, link)
			}

			expect_ascii_line(&p, "$EndPeriodic") or_return
		} else {
			p.cursor = periodic_start
		}
	}

	return gmsh_build_topology(mesh, raw_primary_elements[:], raw_boundary_elements[:], raw_periodic_links[:])
}

//== Gmsh node order -> reference node order

// Reference coordinates of each gmsh node, in gmsh's local order. Gmsh's reference cells coincide with ours
// (Line/Quad/Hex on [-1, 1], Tri/Tet unit simplices); only the numbering differs. Order-1 types use the prefix.
@(private = "file", rodata)
GMSH_LINE := [?]fe.Ref_Vec{{-1, 0, 0}, {1, 0, 0}, {0, 0, 0}}

@(private = "file", rodata)
GMSH_TRI := [?]fe.Ref_Vec{{0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0.5, 0, 0}, {0.5, 0.5, 0}, {0, 0.5, 0}}

@(private = "file", rodata)
GMSH_QUAD := [?]fe.Ref_Vec {
	{-1, -1, 0}, {1, -1, 0}, {1, 1, 0}, {-1, 1, 0}, // vertices
	{0, -1, 0}, {1, 0, 0}, {0, 1, 0}, {-1, 0, 0}, // edges 0-1, 1-2, 2-3, 3-0
	{0, 0, 0},
}

@(private = "file", rodata)
GMSH_TET := [?]fe.Ref_Vec {
	{0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0, 0, 1}, // vertices
	{0.5, 0, 0}, {0.5, 0.5, 0}, {0, 0.5, 0}, {0, 0, 0.5}, {0, 0.5, 0.5}, {0.5, 0, 0.5}, // edges 0-1, 1-2, 2-0, 3-0, 3-2, 3-1
}

@(private = "file", rodata)
GMSH_HEX := [?]fe.Ref_Vec {
	{-1, -1, -1}, {1, -1, -1}, {1, 1, -1}, {-1, 1, -1}, {-1, -1, 1}, {1, -1, 1}, {1, 1, 1}, {-1, 1, 1}, // vertices
	{0, -1, -1}, {-1, 0, -1}, {-1, -1, 0}, {1, 0, -1}, {1, -1, 0}, {0, 1, -1}, // edges 0-1, 0-3, 0-4, 1-2, 1-5, 2-3
	{1, 1, 0}, {-1, 1, 0}, {0, -1, 1}, {-1, 0, 1}, {1, 0, 1}, {0, 1, 1}, // edges 2-6, 3-7, 4-5, 4-7, 5-6, 6-7
	{0, 0, -1}, {0, -1, 0}, {-1, 0, 0}, {1, 0, 0}, {0, 1, 0}, {0, 0, 1}, // faces z-, y-, x-, x+, y+, z+
	{0, 0, 0},
}

@(private = "file", rodata)
GMSH_POINT := [?]fe.Ref_Vec{{0, 0, 0}}

@(private = "file")
gmsh_ref_nodes :: proc(type: Gmsh_Element_Type) -> []fe.Ref_Vec {
	n := GMSH_ELEMENT_NUM_NODES[type]
	#partial switch type {
	case .MSH_LINE_2, .MSH_LINE_3: return GMSH_LINE[:n]
	case .MSH_TRIANGLE_3, .MSH_TRIANGLE_6: return GMSH_TRI[:n]
	case .MSH_QUAD_4, .MSH_QUAD_9: return GMSH_QUAD[:n]
	case .MSH_TETRA_4, .MSH_TETRA_10: return GMSH_TET[:n]
	case .MSH_HEX_8, .MSH_HEX_27: return GMSH_HEX[:n]
	case .MSH_POINT: return GMSH_POINT[:]
	}
	unreachable()
}

// Reference coordinates of the Lagrange nodes of (et, order), in local dof order.
@(private = "file")
ref_node_coords :: proc(et: fe.Element_Type, order: fe.Order, alloc := context.allocator) -> []fe.Ref_Vec {
	bd := fe.Basis_Desc{et, .Lagrange, order}
	out := make([dynamic]fe.Ref_Vec, alloc)
	for d in fe.Dimension {
		if d > fe.element_dim(et) { break }
		if fe.basis_dofs_per_entity(bd, d) == 0 { continue }
		for e in 0 ..< fe.element_num_sub_entities(et, d) {
			for p in fe.basis_entity_functionals(bd, d, e).rule.points {
				append(&out, fe.element_lift_to_parent_reference(et, d, e, p))
			}
		}
	}
	return out[:]
}

// perm[reference local node] = gmsh local node. Cached per gmsh type.
@(private = "file")
node_perm :: proc(cache: ^map[Gmsh_Element_Type][]int, type: Gmsh_Element_Type) -> (perm: []int, ok: bool) {
	if p, found := cache[type]; found { return p, true }

	et, order := gmsh_type_to_element_info(type)
	ref := ref_node_coords(et, order, context.temp_allocator)
	gmsh := gmsh_ref_nodes(type)
	if len(ref) != len(gmsh) {
		log.errorf("Gmsh: %v has %d nodes, reference element expects %d", type, len(gmsh), len(ref))
		return nil, false
	}

	perm = make([]int, len(ref), context.temp_allocator)
	for r, i in ref {
		perm[i] = -1
		for g, j in gmsh {
			diff := g - r
			if abs(diff[0]) + abs(diff[1]) + abs(diff[2]) < 1e-12 { perm[i] = j; break }
		}
		if perm[i] < 0 {
			log.errorf("Gmsh: no %v node at reference position %v", type, r)
			return nil, false
		}
	}
	cache[type] = perm
	return perm, true
}

//== Topology

@(private = "file")
Facet_Key :: [4]int

@(private = "file")
NO_VERT :: max(int)

@(private = "file")
facet_key :: proc(ids: []$T) -> Facet_Key {
	key := Facet_Key{NO_VERT, NO_VERT, NO_VERT, NO_VERT}
	for v, i in ids { key[i] = int(v) }
	slice.sort(key[:len(ids)])
	return key
}

// Edges or faces, deduplicated by vertex set.
@(private = "file")
Entity_Table :: struct {
	ids:       map[Facet_Key]fe.Entity_ID,
	canonical: [dynamic][]fe.Entity_ID, // vertex ids in the order the first cell to reach the entity saw them
	types:     [dynamic]fe.Element_Type,
}

@(private = "file")
entity_lookup :: proc(t: ^Entity_Table, et: fe.Element_Type, verts: []fe.Entity_ID) -> (id: fe.Entity_ID, canonical: []fe.Entity_ID) {
	key := facet_key(verts)
	if existing, ok := t.ids[key]; ok { return existing, t.canonical[existing] }
	id = fe.Entity_ID(len(t.canonical))
	t.ids[key] = id
	append(&t.canonical, slice.clone(verts, context.temp_allocator))
	append(&t.types, et)
	return id, t.canonical[id]
}

@(private = "file")
Topology :: struct {
	fd:             fe.Dimension,
	vertex_of_node: map[int]fe.Entity_ID, // corner nodes only
	tables:         [fe.Dimension]Entity_Table, // dims 1 ..< cell dim
}

// Facet id from any node list whose first entries are its vertices (a gmsh boundary element).
@(private = "file")
find_facet :: proc(topo: ^Topology, type: fe.Element_Type, node_indices: []int) -> (id: fe.Entity_ID, ok: bool) {
	nv := fe.element_num_sub_entities(type, .D0)
	verts: [4]fe.Entity_ID
	for i in 0 ..< nv { verts[i] = topo.vertex_of_node[node_indices[i]] or_return }
	if topo.fd == .D0 { return verts[0], true }
	return topo.tables[topo.fd].ids[facet_key(verts[:nv])]
}

// Canonical vertex ids of a facet.
@(private = "file")
facet_canon :: proc(topo: ^Topology, f: fe.Entity_ID, buf: ^[1]fe.Entity_ID) -> []fe.Entity_ID {
	if topo.fd == .D0 {
		buf[0] = f
		return buf[:]
	}
	return topo.tables[topo.fd].canonical[f]
}

// Vertices are affine iff every node sits at the affine map of its reference position.
@(private = "file")
is_affine :: proc(et: fe.Element_Type, order: fe.Order, nodes: []fe.Entity_ID, coords: [][3]f64) -> bool {
	if et == .Point { return true }
	ref := ref_node_coords(et, order, context.temp_allocator)

	// Axis vertices: those differing from vertex 0 in exactly one reference coordinate.
	x0, r0 := coords[nodes[0]], ref[0]
	J: [3][3]f64 // columns
	for a in 0 ..< int(fe.element_dim(et)) {
		for j in 1 ..< fe.element_num_sub_entities(et, .D0) {
			dr := ref[j] - r0
			single := true
			for b in 0 ..< 3 { if b != a && abs(dr[b]) > 1e-12 { single = false } }
			if single && abs(dr[a]) > 1e-12 {
				J[a] = (coords[nodes[j]] - x0) / dr[a]
				break
			}
		}
	}

	for r, i in ref {
		dr := r - r0
		x := x0 + J[0] * dr[0] + J[1] * dr[1] + J[2] * dr[2]
		diff := x - coords[nodes[i]]
		for k in 0 ..< 3 { if abs(diff[k]) > ALIGNMENT_TOLERANCE { return false } }
	}
	return true
}

@(private = "file")
gmsh_build_topology :: proc(
	mesh: ^fe.Mesh,
	primary: []Raw_Element,
	boundary: []Raw_Element,
	periodic_links: []Raw_Periodic_Link,
) -> bool {
	if mesh.intrinsic_dim < .D1 {
		log.error("Gmsh: mesh must be at least 1D to build topology")
		return false
	}
	cd := mesh.intrinsic_dim

	topo := Topology {
		fd             = cd - fe.Dimension(1),
		vertex_of_node = make(map[int]fe.Entity_ID, context.temp_allocator),
	}
	for &t in topo.tables {
		t.ids = make(map[Facet_Key]fe.Entity_ID, context.temp_allocator)
		t.canonical = make([dynamic][]fe.Entity_ID, context.temp_allocator)
		t.types = make([dynamic]fe.Element_Type, context.temp_allocator)
	}
	perms := make(map[Gmsh_Element_Type][]int, context.temp_allocator)

	n_cells := len(primary)
	mesh.cells = make([]fe.Cell, n_cells)
	mesh.cell_conn = make([]fe.Connectivity, n_cells)
	mesh.cell_nodes = make([][]fe.Entity_ID, n_cells)

	for elem, ci in primary {
		et, _ := gmsh_type_to_element_info(elem.type)
		perm := node_perm(&perms, elem.type) or_return

		cell := &mesh.cells[ci]
		cell.id = fe.Entity_ID(ci)
		cell.region = fe.Region_ID(elem.tags[0]) if len(elem.tags) > 0 else 0
		cell.type = et

		nodes := make([]fe.Entity_ID, len(perm))
		for g, i in perm { nodes[i] = fe.Entity_ID(elem.node_indices[g]) }
		mesh.cell_nodes[ci] = nodes
		cell.affine = is_affine(et, mesh.order, nodes, mesh.nodes)

		conn := &mesh.cell_conn[ci]
		conn^[.D0] = make([]fe.Entity_ID, fe.element_num_sub_entities(et, .D0))
		for &v, i in conn^[.D0] {
			node := int(nodes[i])
			id, found := topo.vertex_of_node[node]
			if !found {
				id = fe.Entity_ID(len(topo.vertex_of_node))
				topo.vertex_of_node[node] = id
			}
			v = id
		}

		// Edges and faces, in reference order, each keyed against its canonical order.
		for d in fe.Dimension {
			if d == .D0 || d >= cd { continue }
			conn^[d] = make([]fe.Entity_ID, fe.element_num_sub_entities(et, d))
			for &id, e in conn^[d] {
				sub := fe.element_sub_entity(et, d, e)
				verts := make([]fe.Entity_ID, len(sub.closure[.D0]), context.temp_allocator)
				for v, k in sub.closure[.D0] { verts[k] = conn^[.D0][v] }

				canon: []fe.Entity_ID
				id, canon = entity_lookup(&topo.tables[d], sub.type, verts)
				key := fe.element_orientation(sub.type, verts, canon)
				if d == .D1 { cell.edge_orientation[e] = key } else { cell.face_orientation[e] = key }
			}
		}

		conn^[cd] = make([]fe.Entity_ID, 1)
		conn^[cd][0] = cell.id
		cell.facets = conn^[topo.fd]
	}

	mesh.n_entities[.D0] = len(topo.vertex_of_node)
	for d in fe.Dimension {
		if d != .D0 && d < cd { mesh.n_entities[d] = len(topo.tables[d].canonical) }
	}
	mesh.n_entities[cd] = n_cells
	n_facets := mesh.n_entities[topo.fd]

	// Incidences in cell order, so the first incidence is the cell that fixed the facet's canonical order.
	facet_inc := make([][dynamic]fe.Facet_Incidence, n_facets, context.temp_allocator)
	for &incs in facet_inc { incs = make([dynamic]fe.Facet_Incidence, 0, 2, context.temp_allocator) }
	for cell in mesh.cells {
		for f, i in cell.facets { append(&facet_inc[f], fe.Facet_Incidence{local_facet = i8(i), cell = cell.id}) }
	}

	boundary_of := make([]fe.Boundary_ID, n_facets, context.temp_allocator)
	slice.fill(boundary_of, fe.Boundary_ID(fe.NOT_A_BOUNDARY))
	for elem in boundary {
		bt, _ := gmsh_type_to_element_info(elem.type)
		f, found := find_facet(&topo, bt, elem.node_indices)
		if !found {
			log.errorf("Gmsh: boundary element (nodes=%v) does not match any facet", elem.node_indices)
			return false
		}
		if len(elem.tags) > 0 { boundary_of[f] = fe.Boundary_ID(elem.tags[0]) }
	}

	total_incidences := 0
	for incs in facet_inc { total_incidences += len(incs) }
	mesh.facets = make([]fe.Facet, n_facets)
	mesh.incidences = make([]fe.Facet_Incidence, total_incidences)

	cursor := 0
	for incs, f in facet_inc {
		affine := true
		for inc in incs { affine &&= mesh.cells[inc.cell].affine }
		ftype := fe.Element_Type.Point if topo.fd == .D0 else topo.tables[topo.fd].types[f]

		facet := &mesh.facets[f]
		facet^ = {
			id              = fe.Entity_ID(f),
			incidence_count = i8(len(incs)),
			incidence_start = cursor,
			info            = {affine = affine, boundary = boundary_of[f], type = ftype},
		}
		copy(mesh.incidences[cursor:], incs[:])
		cursor += len(incs)

		// A 3D facet as an element: its local order is its canonical order, so only its edges orient.
		if topo.fd == .D2 {
			fc := topo.tables[.D2].canonical[f]
			for k in 0 ..< fe.element_num_sub_entities(ftype, .D1) {
				ev := fe.element_sub_entity(ftype, .D1, k).closure[.D0]
				verts := [2]fe.Entity_ID{fc[ev[0]], fc[ev[1]]}
				eid := topo.tables[.D1].ids[facet_key(verts[:])]
				facet.edge_orientation[k] = fe.element_orientation(.Line, verts[:], topo.tables[.D1].canonical[eid])
			}
		}
	}

	if len(periodic_links) > 0 {
		mesh.periodics = gmsh_build_periodicity(&topo, boundary, periodic_links) or_return
	}
	return true
}

// For each master facet sub-entity k of dimension d (facet-local order): maps[d][k] is the matching slave
// sub-entity and orientations[d][k] = element_orientation(type, master's canonical vertices as slave ids,
// slave's canonical vertices). The facet itself is maps[fd] = {0}; vertices carry no orientation.
@(private = "file")
gmsh_build_periodicity :: proc(
	topo: ^Topology,
	boundary: []Raw_Element,
	links: []Raw_Periodic_Link,
) -> (
	periodics: []fe.Periodicity,
	ok: bool,
) {
	entity_to_boundary := make(map[i32]fe.Boundary_ID, context.temp_allocator)
	for elem in boundary {
		if len(elem.tags) < 2 { continue }
		entity_to_boundary[elem.tags[1]] = fe.Boundary_ID(elem.tags[0])
	}

	result := make([]fe.Periodicity, len(links))

	for link, li in links {
		// Vertex correspondence both ways (high-order nodes are not vertices and are skipped).
		slave_of := make(map[fe.Entity_ID]fe.Entity_ID, context.temp_allocator)
		master_of := make(map[fe.Entity_ID]fe.Entity_ID, context.temp_allocator)
		for pr in link.pairs {
			sv, s_ok := topo.vertex_of_node[pr[0]]
			mv, m_ok := topo.vertex_of_node[pr[1]]
			if s_ok && m_ok {
				slave_of[mv] = sv
				master_of[sv] = mv
			}
		}

		pairs := make([dynamic]fe.Periodic_Pair)

		for elem in boundary {
			if len(elem.tags) < 2 || elem.tags[1] != link.slave_tag { continue }
			et, _ := gmsh_type_to_element_info(elem.type)

			slave, found_slave := find_facet(topo, et, elem.node_indices)
			if !found_slave {
				log.errorf("Gmsh: $Periodic slave element (nodes=%v) does not match any facet", elem.node_indices)
				return nil, false
			}
			sbuf, mbuf: [1]fe.Entity_ID
			sc := facet_canon(topo, slave, &sbuf)

			mverts := make([]fe.Entity_ID, len(sc), context.temp_allocator)
			for v, i in sc {
				mverts[i] = master_of[v] or_else -1
				if mverts[i] < 0 {
					log.errorf("Gmsh: $Periodic vertex %d has no master correspondence", v)
					return nil, false
				}
			}
			master: fe.Entity_ID
			found_master: bool
			if topo.fd == .D0 {
				master, found_master = mverts[0], true
			} else {
				master, found_master = topo.tables[topo.fd].ids[facet_key(mverts)]
			}
			if !found_master {
				log.errorf("Gmsh: $Periodic master facet (verts=%v) does not match any facet", mverts)
				return nil, false
			}
			mc := facet_canon(topo, master, &mbuf)

			pair := fe.Periodic_Pair{master = master, slave = slave}
			for d in fe.Dimension {
				if d > topo.fd { break }
				n := fe.element_num_sub_entities(et, d)
				pair.maps[d] = make([]int, n)
				if d != .D0 { pair.orientations[d] = make([]u8, n) }

				for k in 0 ..< n {
					lv := fe.element_sub_entity(et, d, k).closure[.D0]
					master_verts := make([]fe.Entity_ID, len(lv), context.temp_allocator)
					translated := make([]fe.Entity_ID, len(lv), context.temp_allocator)
					for v, i in lv {
						master_verts[i] = mc[v]
						translated[i] = slave_of[mc[v]]
					}
					want := facet_key(translated)

					sk := -1
					for k2 in 0 ..< n {
						lv2 := fe.element_sub_entity(et, d, k2).closure[.D0]
						cand := make([]fe.Entity_ID, len(lv2), context.temp_allocator)
						for v, i in lv2 { cand[i] = sc[v] }
						if facet_key(cand) == want { sk = k2; break }
					}
					if sk < 0 {
						log.errorf("Gmsh: $Periodic could not match sub-entity %d (dim %v) of facet %d", k, d, master)
						return nil, false
					}
					pair.maps[d][k] = sk
					if d == .D0 { continue }

					// canonical orders of both entities, the master's expressed in slave vertex ids
					t := &topo.tables[d]
					mcanon := t.canonical[t.ids[facet_key(master_verts)]]
					scanon := t.canonical[t.ids[want]]
					mcanon_in_slave := make([]fe.Entity_ID, len(mcanon), context.temp_allocator)
					for v, i in mcanon { mcanon_in_slave[i] = slave_of[v] }
					pair.orientations[d][k] = fe.element_orientation(fe.element_sub_entity(et, d, k).type, mcanon_in_slave, scanon)
				}
			}
			append(&pairs, pair)
		}

		result[li] = fe.Periodicity {
			slave     = entity_to_boundary[link.slave_tag] or_else fe.Boundary_ID(fe.NOT_A_BOUNDARY),
			master    = entity_to_boundary[link.master_tag] or_else fe.Boundary_ID(fe.NOT_A_BOUNDARY),
			transform = link.transform,
			pairs     = pairs[:],
		}
	}

	return result, true
}
